  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8086
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: healthflow
      SPRING_RABBITMQ_PASSWORD: healthflow
    ports:
      - "8086:8086"
    networks:
      - healthflow-network

    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "service=gateway"