spring.application.name=auth-service
server.port=${SERVER_PORT:8085}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5438/auth}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auth_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:auth_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

api.security.token.secret=${JWT_SECRET:healthflow-secret-key}