spring.application.name=notification-service
server.port=${SERVER_PORT:8086}

# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:healthflow}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:healthflow}

# Queue que o notification-service vai consumir
healthflow.rabbitmq.appointment-created-queue=notification.appointment.created.queue

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha