services:
  gateway:
    build:
      context: .
    container_name: gateway
    environment:
      SERVER_PORT: 8080

      AUTH_SERVICE_URL: http://host.docker.internal:8085
      PATIENT_SERVICE_URL: http://host.docker.internal:8081
      DOCTOR_SERVICE_URL: http://host.docker.internal:8082
      SCHEDULING_SERVICE_URL: http://host.docker.internal:8083
      TRIAGE_SERVICE_URL: http://host.docker.internal:8084

    ports:
      - "8080:8080"