  gateway:
    build:
      context: ./gateway
    container_name: gateway
    depends_on:
      - auth-service
      - patient-service
      - doctor-service
      - scheduling-service
      - triage-service
      - notification-service
      - audit-service
      - jaeger
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: gateway

      JWT_SECRET: healthflow-secret-key

      AUTH_SERVICE_URL: http://auth-service:8085
      PATIENT_SERVICE_URL: http://patient-service:8081
      DOCTOR_SERVICE_URL: http://doctor-service:8082
      SCHEDULING_SERVICE_URL: http://scheduling-service:8083
      TRIAGE_SERVICE_URL: http://triage-service:8084
      NOTIFICATION_SERVICE_URL: http://notification-service:8086
      AUDIT_SERVICE_URL: http://audit-service:8087

      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: 1.0
      MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "8080:8080"
    networks:
      - healthflow-network