services:
  triage-postgres:
    image: postgres:16-alpine
    container_name: triage-postgres
    environment:
      POSTGRES_DB: triage
      POSTGRES_USER: triage_user
      POSTGRES_PASSWORD: triage_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5437:5432"
    volumes:
      - triage_postgres_data:/var/lib/postgresql/data
    networks:
      - triage-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U triage_user -d triage"]
      interval: 10s
      timeout: 5s
      retries: 5

  triage-service:
    build:
      context: .
    container_name: triage-service
    depends_on:
      - triage-postgres
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://triage-postgres:5432/triage
      SPRING_DATASOURCE_USERNAME: triage_user
      SPRING_DATASOURCE_PASSWORD: triage_password

      SERVICES_PATIENT_URL: http://host.docker.internal:8081
      SERVICES_SCHEDULING_URL: http://host.docker.internal:8083
    ports:
      - "8084:8084"
    networks:
      - triage-network

volumes:
  triage_postgres_data:
    driver: local

networks:
  triage-network:
    driver: bridge