services:
  scheduling-postgres:
    image: postgres:16-alpine
    container_name: scheduling-postgres
    environment:
      POSTGRES_DB: scheduling
      POSTGRES_USER: scheduling_user
      POSTGRES_PASSWORD: scheduling_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5436:5432"
    volumes:
      - scheduling_postgres_data:/var/lib/postgresql/data
    networks:
      - scheduling-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scheduling_user -d scheduling"]
      interval: 10s
      timeout: 5s
      retries: 5

  scheduling-service:
    build:
      context: .
    container_name: scheduling-service
    depends_on:
      - scheduling-postgres
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://scheduling-postgres:5432/scheduling
      SPRING_DATASOURCE_USERNAME: scheduling_user
      SPRING_DATASOURCE_PASSWORD: scheduling_password

      SERVICES_PATIENT_URL: http://host.docker.internal:8081
      SERVICES_DOCTOR_URL: http://host.docker.internal:8082
    ports:
      - "8083:8083"
    networks:
      - scheduling-network

volumes:
  scheduling_postgres_data:
    driver: local

networks:
  scheduling-network:
    driver: bridge


    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "service=gateway"