spring.application.name=doctor-service
spring.datasource.url=jdbc:postgresql://localhost:5435/doctor
spring.datasource.username=doctor_user
spring.datasource.password=doctor_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration