spring.application.name=scheduling-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5436/scheduling
spring.datasource.username=scheduling_user
spring.datasource.password=scheduling_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

services.patient.url=http://localhost:8081
services.doctor.url=http://localhost:8082