services:
  patient-postgres:
    image: postgres:16-alpine
    container_name: patiente-postgres
    environment:
      POSTGRES_DB: patiente
      POSTGRES_USER: post_user
      POSTGRES_PASSWORD: post_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - patient_postgres_data:/var/lib/postgresql/data
    networks:
      - patient-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U post_user -d patiente"]
      interval: 10s
      timeout: 5s
      retries: 5

  patient-service:
    build:
      context: .
    container_name: patient-service
    depends_on:
      - patient-postgres
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-postgres:5432/patiente
      SPRING_DATASOURCE_USERNAME: post_user
      SPRING_DATASOURCE_PASSWORD: post_password
    ports:
      - "8081:8081"
    networks:
      - patient-network

volumes:
  patient_postgres_data:
    driver: local

networks:
  patient-network:
    driver: bridge