services:
  doctor-postgres:
    image: postgres:16-alpine
    container_name: doctor-postgres
    environment:
      POSTGRES_DB: doctor
      POSTGRES_USER: doctor_user
      POSTGRES_PASSWORD: doctor_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - doctor_postgres_data:/var/lib/postgresql/data
    networks:
      - doctor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doctor_user -d doctor"]
      interval: 10s
      timeout: 5s
      retries: 5

  doctor-service:
    build:
      context: .
    container_name: doctor-service
    depends_on:
      - doctor-postgres
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://doctor-postgres:5432/doctor
      SPRING_DATASOURCE_USERNAME: doctor_user
      SPRING_DATASOURCE_PASSWORD: doctor_password
    ports:
      - "8082:8082"
    networks:
      - doctor-network

volumes:
  doctor_postgres_data:
    driver: local

networks:
  doctor-network:
    driver: bridge


    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "service=gateway"