spring.application.name=patient-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5434/patiente
spring.datasource.username=post_user
spring.datasource.password=post_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
port:

spring.flyway.enabled=true