  audit-service:
    build:
      context: ./audit-service
    container_name: audit-service
    depends_on:
      audit-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SERVER_PORT: 8087

      SPRING_DATASOURCE_URL: jdbc:postgresql://audit-postgres:5432/audit
      SPRING_DATASOURCE_USERNAME: audit_user
      SPRING_DATASOURCE_PASSWORD: audit_password

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: healthflow
      SPRING_RABBITMQ_PASSWORD: healthflow
    ports:
      - "8087:8087"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "service=audit-service"
    networks:
      - healthflow-network

  gateway:
    build:
      context: ./gateway
    container_name: gateway